### ISSUE TITLE
как создать реферальную ссылку, приложение ломается при добавление парaметров в url

### ISSUE THREAD

**Issue by bks-kristin** [VKCOM/vk-mini-apps-router#196]
Есть задача: сделать реферальную ссылку на приложение для каждого пользователя, предполагается использование vk_id пользователя как параметр в url вида https://m.vk.com/app123#/:{vk_id}
Есть проблема: приложение не открывается если добавляем сторонний параметр, потому что воспринимает его как пусть и логично не может найти панель под указанным именем, был вариант добавить переменную vk_id в пути, но она меняется для каждого пользователя и не возможно отловить id по которому пришёл пользователь, соответственно никак не осуществить проверку приглашения пользователей. Какие могут быть решения у данной проблемы?

**Comment by nshvyryaev** [comment]
Добрый день!
Не до конца понял кейс.

В url вида [https://m.vk.com/app123#/:{vk_id}](https://m.vk.com/app123#/:%7Bvk_id%7D) идентификатор пользователя становится параметром пути - это вполне валидное использование. 

Если нужно, чтобы параметр не влиял на путь - можно пробросить его через search params - после знака ? [https://m.vk.com/app123#/?ref_id=:{vk_id}](https://m.vk.com/app123#/?ref_id=:%7Bvk_id%7D)

Если дело в том, что в хэше борются сторонний параметр запуска мини-приложения и путь - это можно решить с помощью createHashParamRouter, тогда у вас путь займет один из параметров хэша и можно будет пробрасывать другие в виде [https://m.vk.com/app123#path=/&ref_id=:{vk_id}](https://m.vk.com/app123#path=/&ref_id=:%7Bvk_id%7D)

Если не один из вариантов вам не подходит, прошу подробнее описать случай.

**Comment by bks-kristin** [comment]
Прошу прощения, за то, что не совсем понятно объяснила то, что надо получить. Надо чтобы пробрасывался параметр, и при переходе по новой ссылке параметр можно было вытащить. Вариант с createHashParamRouter сработал, спасибо большое! Только ещё один вопрос, с помощью чего можно добавить параметр, являющийся строкой (в моём случае ref_id=vk_id), нашла withRouter, но до конца не поняла поможет ли.

**Comment by nshvyryaev** [comment]
withRouter нужен если у вас приложение на классах написано. Можно почитать https://reactdev.ru/types/054/

Если написано функциями можно использовать хуки начинающиеся с `use...`. Ну и это не связано с параметрами непосредственно.

Строковый параметр можно пробросить через параметр пути или через search параметр. Посмотрите на useSearchParams и на опцию keepSearchParams в RouteNavigator.push

**Comment by bks-kristin** [comment]
Спасибо большое, вы очень помогли мне! В итоге использую createHashParamRouter для создания реферальной ссылки.
