### ISSUE TITLE
Сбрасывается scroll position при переходе назад

### ISSUE THREAD

**Issue by svyatoslavpavlov** [VKCOM/vk-mini-apps-router#230]
Собственно, при работе с длинными списками при детальном просмотре и переходе назад приходится скроллить сначала.

**Comment by nshvyryaev** [comment]
Добрый день!
Сейчас есть такая проблема. Спланируем и возьмем в работу задачу.

**Comment by Yarkin13** [comment]
> Собственно, при работе с длинными списками при детальном просмотре и переходе назад приходится скроллить сначала.

Добрый день, прошу приложить видео с примером дефекта.

**Comment by svyatoslavpavlov** [comment]
> > Собственно, при работе с длинными списками при детальном просмотре и переходе назад приходится скроллить сначала.

> 
> Добрый день, прошу приложить видео с примером дефекта.


https://github.com/VKCOM/vk-mini-apps-router/assets/7815563/b4cd537f-1c89-4c1b-91ac-9111f16d5f36

**Comment by svyatoslavpavlov** [comment]
> Добрый день!
> Сейчас есть такая проблема. Спланируем и возьмем в работу задачу.

Можете поделиться примерными сроками?

**Comment by Yarkin13** [comment]
> > > Собственно, при работе с длинными списками при детальном просмотре и переходе назад приходится скроллить сначала.
> 
> > Добрый день, прошу приложить видео с примером дефекта.
> 
>  Screen.Recording.2023-09-30.at.10.06.40.mov

Пришлите пожалуйста структуру навигации.

**Comment by svyatoslavpavlov** [comment]
`
export const routes = RoutesConfig.create([
  createView(DEFAULT_VIEW, [ 
...


    createPanel(DEFAULT_VIEW_PANELS.EVENT, "/event/:event", [], ["event"]),
    createPanel(DEFAULT_VIEW_PANELS.GROUP_SCHEDULE, `/${DEFAULT_VIEW_PANELS.GROUP_SCHEDULE}`, [
      createTab(GROUP_SCHEDULE_TABS.UPCOMING, `/${DEFAULT_VIEW_PANELS.GROUP_SCHEDULE}/`),
      createTab(GROUP_SCHEDULE_TABS.PAST, `/${DEFAULT_VIEW_PANELS.GROUP_SCHEDULE}/${GROUP_SCHEDULE_TABS.PAST}`),
      createTab(GROUP_SCHEDULE_TABS.TAG, `/${DEFAULT_VIEW_PANELS.GROUP_SCHEDULE}/${GROUP_SCHEDULE_TABS.TAG}/:tag`, [], ["tag"]),
    ]),
...
`

**Comment by svyatoslavpavlov** [comment]
Кажется, я понял, в чем проблема:
Значение текущего таба сбрасывается при переходе на другой экран

и если делать по образцу через if-else, то при переходе на details экран список будет скрыт, а при переходе назад снова появится

**Comment by nshvyryaev** [comment]
Звучит логично, посмотрим на этот случай. Если действительно так, нужно будет чинить совместно с VKUI

**Comment by pasha-nikitin-2003** [comment]
> Собственно, при работе с длинными списками при детальном просмотре и переходе назад приходится скроллить сначала.

Добрый день! Проблема может заключаться в неправильном расположении панелей внутри View. VKUI восстановит скролл, если компонент панели, на которую вы возвращаетесь, будет в верстке находиться выше компонента  панели, с которой вы возвращаетесь. То есть панель GROUP_SCHEDULE, должна идти раньше панели EVENT в верстке внутри View.

Также могут быть и другие причины, почему отсутствует восстановление скролла, например:
  - изменение внутренних стилей компонентов vkui.  
  - верстка внутри самой панели, которая мешает браузеру выполнить window.scrollTo(...).  

Если вышеперечисленные варианты не помогут, то мы можем посмотреть код проекта, чтобы дать более конкретный ответ.

**Comment by svyatoslavpavlov** [comment]
Поменял немного структуру, проблема действительно отпала
