### ISSUE TITLE
Предложение добавить функцию блокировки перехода назад/вперёд

### ISSUE THREAD

**Issue by Andrey-Kuzmichev** [VKCOM/vk-mini-apps-router#242]
Поскольку в компоненте VKUI, доступном по ссылке https://vkcom.github.io/VKUI/#/ScreenSpinner, имеется элемент ScreenSpinner, который блокирует пользовательский доступ ко всем элементам под ним, предлагаю внести усовершенствование, добавив функцию блокировки переходов назад и вперед в браузере, чтобы пользователь не мог случайно закрыть экран загрузки.

В настоящее время в компоненте ScreenSpinner имеется свойство "state", которое предоставляет пользователю управление состоянием загрузки. Было бы логичным разрешить изменение этого состояния только через указанное свойство, предотвращая закрытие экрана загрузки в любой момент.

Или использовать в любом другом кейсе.

**Comment by nshvyryaev** [comment]
Блокировку сделать можно, но едва ли стоит привязывать ее к загрузке. Например, если загрузка идет долго, пользователь наверняка захочет шагнуть назад. В целом, мы планируем добавить механизм блокировки перехода, но управление логикой блокировки будет на стороне приложения. Так, например, можно будет заблокировать и спиннер. Задача есть в бэклоге проекта, еще не спланирована.

**Comment by pasha-nikitin-2003** [comment]
Здравствуйте, добавили возможность блокировать навигацию при помощи routeNavigator.block(callback), пример с использованием добавили в examples. В ближайшее время в документации появится полное описание метода.
