### ISSUE TITLE
Неправильно (?) обрабатывает горячий старт приложения

### ISSUE THREAD

**Issue by svyatoslavpavlov** [VKCOM/vk-mini-apps-router#276]
С видео, возможно, станет яснее: если открыть приложение с виджета "на гроячую", без рестарта, то выдает ошибку, при этом если открыть эту жу страницу холодным стартом - все ок. Работает через раз будто. Судя по логам - адрес будто суммируется. Хэш получается иногда такой #event/917131/event/12345 вместо просто #event/12345
Адрес в виджете стоит корректный (собственно, рестарт это показывает)

https://github.com/VKCOM/vk-mini-apps-router/assets/7815563/67ecfee6-faa6-42b5-872f-ad8f0da50306

**Comment by svyatoslavpavlov** [comment]
Проверил VKWebAppLocationChanged и VKWebAppChangeFragment - приходят правильные значения вида event/12345 или event/917131

**Comment by pasha-nikitin-2003** [comment]
Здравствуйте! Не получилось воспроизвести баг, ни на ios, ни на android версиях приложения.  

Для тестирования создал [сообщество](https://vk.com/public223023129), в котором прикрепил, как прямые ссылки на разные страницы аппа, так и прокси ссылки(vk.cc).  В качестве мини-аппа взял шаблон мини приложения [github](https://github.com/VKCOM/vk-mini-apps-examples).

К сожалению, у нас нет возможности воспроизвести баг на виджетах "Афиши", могли бы вы указать альтернативные шаги или расшарить код приложения?

**Comment by svyatoslavpavlov** [comment]
Нашел различия:
#event/12345
#/event/12345

Если добавить после слэш в начало адреса, то все ок, без него работает некорректно

**Comment by nshvyryaev** [comment]
Поведение библиотеки верное. Вы использовали неверный формат относительной ссылки ссылок.

Подробнее почитать о разных относительных и абсолютных ссылках можно тут
https://htmlbook.ru/samhtml/ssylki/absolyutnye-i-otnositelnye-ssylki#:~:text=%D0%90%D0%B4%D1%80%D0%B5%D1%81%20%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B8%20%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%BA%D0%B0%D0%BA,%D0%BA%D0%BE%D1%80%D0%BD%D1%8F%20%D1%81%D0%B0%D0%B9%D1%82%D0%B0%20%D0%B8%D0%BB%D0%B8%20%D1%82%D0%B5%D0%BA%D1%83%D1%89%D0%B5%D0%B3%D0%BE%20%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0.
