### ISSUE TITLE
[BUG] При вызове routeNavigator.push "из кода" url меняется, а перехода на страницу нет

### ISSUE THREAD

**Issue by dsedinkin** [VKCOM/vk-mini-apps-router#287]
Вызываю routeNavigator.push в кнопке и переход на панельку срабатывает. При вызове из кода routeNavigator.push в url значение меняется, но переход не срабатывает.

На текущий момент полечилось все с использованием window.location.reload(), но я рассматриваю это как временное решение.

![1rZ8lixO9rg](https://github.com/VKCOM/vk-mini-apps-router/assets/62930989/5e6c35d7-d1ac-47e8-9041-2aa46c5ff357)
![6-UkCxNH5bY](https://github.com/VKCOM/vk-mini-apps-router/assets/62930989/467d6d2c-ca32-410e-b73e-0265a28d118c)
![C47G5ZT_e_4](https://github.com/VKCOM/vk-mini-apps-router/assets/62930989/ea732f2f-23c3-4b55-a838-a5be476cef48)
![FJroU8NvrGw](https://github.com/VKCOM/vk-mini-apps-router/assets/62930989/8e794ed6-f14f-4d3c-b4c4-284492402a98)

**Comment by pasha-nikitin-2003** [comment]
На данный момент баг не отслеживается.
