### ISSUE TITLE
Скролл восстанавливается слишком рано

### ISSUE THREAD

**Issue by nikitakoschelenko** [VKCOM/vk-mini-apps-router#292]
При переходе назад между панелями внутри `View` во время начала анимации происходит восстановление скролла, из-за чего страница, с которой происходит переход назад, резко скроллится вниз. Видео-демонстрация бага:

https://github.com/VKCOM/vk-mini-apps-router/assets/24193020/5a7cbafc-53bf-4438-8559-e3d7260b5be7

[Ссылка](https://codesandbox.io/s/vkui-vkma-router-scroll-back-bug-fggw63) на пример кода с багом (лучше открывать в [отдельной вкладке](https://fggw63.csb.app/), иначе история криво работает).

Воспроизводится на платформах IOS и Android (где есть анимация). При использовании свайпбэка на IOS панель меняется корректно. В VKUI без роутера также не воспроизводится.

**Comment by nshvyryaev** [comment]
Здравствуйте!
Исследуем на следующей неделе.

**Comment by pasha-nikitin-2003** [comment]
Здравствуйте, спасибо за подробное описание бага, в версии 1.3.0 устранили проблему.
