### ISSUE TITLE
Некорректно работает роутер

### ISSUE THREAD

**Issue by ExLineP** [VKCOM/vk-mini-apps-router#301]
При создании панелей во View и переходе по панелям через push или через смену url страницы происходит наложение двух страниц, но при перезагрузке странице все возвращается в нормальное состояние: показывается только одна нужная страница. Могу предположить, что нужной панели не дается нужный класс активности.

Использую новейшую версию роутера.
Код:
```
function App() {
	const { view: activeView, panel: activePanel } = useActiveVkuiLocation();
	return (
		<Root activeView={activeView}>
			<View nav={"default_view"} activePanel={activePanel}>
				<Panel nav="home_panel">
					<div>123</div>
				</Panel>
				<Panel nav="chart_panel">
					<div>CHART</div>
				</Panel>
			</View>
		</Root>
	);
}
```

**Comment by nshvyryaev** [comment]
Здравствуйте!
Это выглядит как самый базовый способ использования. Пробовали запускать пример приложения, расположенный тут: https://github.com/VKCOM/vk-mini-apps-router/tree/master/examples/vk-mini-apps-router-example?

Если и пример не запускается - дайте знать, в каком окружении запускаете.

Если пример работает - проверьте логику подключения, структуру компонентов, настройку путей, версии библиотек.

**Comment by ExLineP** [comment]
@nshvyryaev Да, работает, но там используется версия 1.2.0, а не 1.3.1

**Comment by nshvyryaev** [comment]
попробуй обновить до 1.3.1, пожалуйста. До выпуска 1.3.1 мы прогоняли с ней пример - работало

**Comment by nshvyryaev** [comment]
а какая версия VKUI?

**Comment by ExLineP** [comment]
VKUI 5.10.0

Немного не понял как сделать репродьюс с useState

**Comment by pasha-nikitin-2003** [comment]
Можете посмотреть примеры на typescript и  javascript [здесь](https://github.com/VKCOM/create-vk-mini-app/tree/master/templates)

**Comment by ExLineP** [comment]
В примерах React 17 и CRA, который, мягко говоря, устарел.

**Comment by ExLineP** [comment]
Посмотрите, пожалуйста, как работает в роутер в Vite и 18 реакте, по крайней мере не только у меня появляются проблемы с роутером.

**Comment by pasha-nikitin-2003** [comment]
> В примерах React 17 и CRA, который, мягко говоря, устарел.

Это пример переключения панелей без роутера, средствами только VKUI. Этот пример будет также хорошо работать с любыми сборщиками и 18 React. Такой же пример можно найти в [документации  VKUI](https://vkcom.github.io/VKUI/#/View).

Роутер по сути является оберткой над useState из указанных выше примеров, т.е. роутер в зависимости от адреса страницы определяет активную панель. Логика переходов и отображения лежит на VKUI.

VKUI отображает на странице в мобильной версии сайта сразу 2 панели для поддержки анимаций. Возможно существуют и другие причины, лучше узнать об этом у команды [VKUI](https://github.com/VKCOM/VKUI)

Если при переходах на mvk возникает визуальный баг или же сборка через vite не запускается, предоставьте, пожалуйста, полное описание проблемы и мы возьмем баг в работу.
