### ISSUE TITLE
не получается импортировать BlockerFunction

### ISSUE THREAD

**Issue by scffs** [VKCOM/vk-mini-apps-router#328]
![image](https://github.com/VKCOM/vk-mini-apps-router/assets/67464545/c148c458-dd2f-4aff-baa1-7066b5a5b128)

версия 1.4.0

**Comment by nshvyryaev** [comment]
Добрый день!
Сегодня починим в 1.4.1

**Comment by pasha-nikitin-2003** [comment]
Исправлено в 1.4.1
