### ISSUE TITLE
Передача metaParams в RouteNavigator.back

### ISSUE THREAD

**Issue by dsedinkin** [VKCOM/vk-mini-apps-router#362]
В методе RouteNavigator.push, есть возможность передавать metaParams (https://dev.vk.com/ru/libraries/router/reference/hooks/useMetaParams), но при RouteNavigator.back их нет.

Приходиться для возвращения на предыдущую страницу использовать RouteNavigator.push, чтоб сохранять параметры.

**Comment by nshvyryaev** [comment]
Добрый день!
Хук useMetaParams() возвращает значение location.state текущей записи history в браузере. 

Именно поэтому при выполнении Push и Replace можно передать metaParams - они будут записаны в state. Переход назад через back не меняет запись, поэтому нельзя туда передать metaParams.

То есть по идее, шаг назад не должен приносить новой информации, напротив, он возвращает некое объявленное ранее состояние. Поэтому в back нельзя передать дополнительные данные. Если предыдущую запись нужно изменить предыдущую запись - можно выполнить метод runSync  экзепляра RouteNavigator и сделать внутри него back + replace.

Мы сохраним это поведение.

Привожу методы навигации для референса (на них основана навигация)
https://developer.mozilla.org/en-US/docs/Web/API/History/pushState
https://developer.mozilla.org/en-US/docs/Web/API/History/back
