### ISSUE TITLE
[Bug]: поломанная навигация вперед

### ISSUE THREAD

**Issue by scffs** [VKCOM/vk-mini-apps-router#385]
### Описание

в офф примере от ВК ([тык](https://vk.com/app51654068#/)) при клике на фильтры, закрытие их через системную кнопку назад и последующим нажатии вперед, фильтры не открываются 

### Версия vk-mini-apps-router

1.4.2 и 1.4.3

### Платформа

Web

### Браузер и версия

last edge / chrome

### Шаги воспроизведения

1. нажать на фильтр
2. закрыть системной кнопкой
3. нажать системную вперед

### Ожидаемое поведение

открываются фильтры

### Приложение

https://vk.com/app51654068#/

**Comment by nshvyryaev** [comment]
Добрый день!

Это не баг, мы целенаправленно запретили шагать вперед на попауты. Фильтры открываются в попауте, закрытие по шагу назад с попаутами важно, а вот открывать их по шагу вперед может создавать проблемы. Потому что попауты привязаны к определенному действию и по шагу вперед часто может быть не очевидно, какое именно действие открыло попаут. Снова открыть фильтры лучше не шагом вперед, а нажатием на сами фильтры.

Задачу закрываю. Если у вас есть запрос на изменение поведения, вы можете открыть ее снова. Но на текущий момент у нас больше запросов от разработчиков на дейсвующее поведение, будем рассматривать изменение только если запросов на переход вперед станет больше.

**Comment by scffs** [comment]
> Это не баг, мы целенаправленно запретили шагать вперед на попауты.

Тогда почему стрелка вперед активна?

**Comment by nshvyryaev** [comment]
Из-за технических ограничений браузерного АПИ. Для попаута существует запись в истории навигации. Когда мы делаем шаг назад, она остается, но мы блокируем шаг вперед. Нельзя удалить запись из истории. Чтобы этой стрелки не было, надо сделать 2 шага назад и запушить новую запись. Но при лишнем шаге назад можно вывалиться из приложения и все сломается.

**Comment by nshvyryaev** [comment]
Если модалка без адреса - она так же как и попап не откроется. Если модалка имеет свой путь - откроется.

То есть модалки с адресом ведут себя как страницы в навигации, а модалки без - как попапы.
