### ISSUE TITLE
[Bug]: Некорректная работа runSync

### ISSUE THREAD

**Issue by ivansekisov-vk** [VKCOM/vk-mini-apps-router#425]
### Проблема
Не получается сделать последовательно смену страницы с последующим открытием модального окна. 

### Демо
https://codesandbox.io/p/sandbox/laughing-bas-jzpg2t

### Версия vk-mini-apps-router

1.4.5

**Comment by pasha-nikitin-2003** [comment]
Добрый вечер, взяли в работу!

**Comment by pasha-nikitin-2003** [comment]
Исправлено в версии 1.4.6
