### ISSUE TITLE
[Bug]: Не открываются модальные окна если state строка

### ISSUE THREAD

**Issue by DimaPopov** [VKCOM/vk-mini-apps-router#432]
### Описание

Если передать state при навигации строкой, а не объектом, то вызов `showModal `будет невозможен. 

### Версия vk-mini-apps-router

1.4.6

### Шаги воспроизведения

```JS
routeNavigator.replace('/login', {
  state: pathname + searchParams
});
```

При вызове:
```JS
routeNavigator.showModal("test")
```
Приводит к ошибке:
```
@vkontakte_vk-mini-apps-router.js?v=41b48120:3973 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'showModal' in /login
    at isModalShown (@vkontakte_vk-mini-apps-router.js?v=41b48120:3973:50)
    at DefaultRouteNavigator.showModal (@vkontakte_vk-mini-apps-router.js?v=41b48120:4605:16)
```

### Ожидаемое поведение

При переходе со `state` в виде строки в консоль выводится предупреждение о том, что state должен быть объектом или `showModal` корректно обрабатывает подобные случаи

**Comment by pasha-nikitin-2003** [comment]
Добрый вечер! Спасибо за обращение, добавим дополнительную проверку.
