### ISSUE TITLE
[Feature]: Расширить интерфейс routeNavigator.back()

### ISSUE THREAD

**Issue by Kritolan** [VKCOM/vk-mini-apps-router#434]
Хотелось бы расширить интерфейс функции возврата для поддержки указания целевой страницы. Это необходимо для более корректной работы кнопок назад, в случае когда страницы ниже по иерархии открываются по прямой ссылке.

# Пример
Есть простая иерархия страниц: Главная -> Страница с кнопкой назад -> Модальное окно. Пользователь открывает модальное окно по прямой сылке. Затем закрывает его и оказывается на странице с кнопкой назад. Нажимает кнопку назад.

# Текущее поведение
Откроется модальное окно.

# Ожидаемое поведение
Произойдет переход на Главную.

# Предлагаемое решение
Расширить интерфейс `routeNavigator.back()` добавив опциональный параметр `target`. При переходе смотреть адрес предыдущей страницы . Если он совпадает с `target` - выполнять переход назад. В противном случае выполнять `push` в `target`.

**Comment by nshvyryaev** [comment]
Здравствуйте!

Браузер не дает возможности увидеть данные записи в истории. Поэтому, при нажатии кнопки назад не получится посмотреть адрес предыдущей страницы. Это возможно, только если выполнить переход, однако, в этом случае, есть риск вывалится из приложения вовсе.

Из уже имеющихся инструметнтов вы можете воспользоваться [настройкой иерархии страниц и параметром inflate= true](https://dev.vk.com/ru/libraries/router/reference/components/RouterProvider#%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F) в адресе открываемой страницы. Так вы сможете получить желаемое поведение при переходе по прямой ссылке.

Другой вариант - в модальном окне в ме, в случае входа по прямой ссылке проверять useFirstPageCheck и использовать replaceState вместо hideModal. Тогда на панели useFirstPageCheck вернет true и кнопкой назад вы сможете сделать условно replace или push.

Мы со своей стороны рассмотрим возможность выполнения hideModal с помощью replace вместо push.

**Comment by Kritolan** [comment]
Браузер не дает, но роутер может собирать эту историю самостоятельно. Он уже делает что-то похоже в `panelsHistory` для целей анимации, но можно и расширить ведь.

`inflate` в целом может решить проблему, но только в случае, если мы контроллируем распространение внешних ссылок, а это не самая простая задача т.к. пользователи очень любят делиться просто текущим адресом браузера.

Вариант с модалкой лишь пример. Модалку можно заменить на любую другую страницу, где есть push на страницу с кнопкой назад. Например при наличии перехода по `breadcrumbs`. Тут даже изначальный переход по прямой ссылке не нужен и соотвественно `inflate` никак не поможет,

При этом ведение истории переходов на стороне роутера с ограниченной глубинной вполне закрывает оба сценария и не сказывается на производительности. Нужен все тот же массив панелей (т.к. параметры адресов нам тут не нужны), к которому добавить контроль повторяющихся панелей и сделать этот массив глобальным на весь роутер, а не в пределах `view`. Тут еще можно понабрасывать деталей, но в целом идея думаю понятна.

**Comment by nshvyryaev** [comment]
Идея понятна. Однако, кейс с переходом по прямой ссылке не так уже сложно обыграть на стороне приложения через useFirstPageCheck. Чаще всего такой переход ведет сразу на главную. Но даже если нужно два перехода - это тоже реализуемо, выше я указал алгоритм. С модальным окном сейчас получается не очень удобно, можно сделать попроще на нашей стороне, скорее всего.

Распространять push на back как практику и накручивать логику сравнения цели шага назад и запоминания истории в роутере выглядит чрезмерным усложнением для специфичной задачи.

В примере про `breadcrumbs` речь про то, что на них будет висеть push, и, после перехода по ним, кнопка "назад" будет возвращать "вперед"? Если да, то для браузера это ожидаемое поведение. На мобильных устройствах это поведение разнится от приложения к приложению. Если вы в приложении хотите что-то нестандартное - это можно настроить на стороне приложения.

**Comment by Kritolan** [comment]
Речь всего лишь про то, чтобы компонент, который выглядит как кнопка назад и действовал как кнопка назад и при нажатии показывал предыдущую панель, по возможности использовав переход по истории.

Мне кажется это довольно инуитивное поведение, нежели что-то не стандартное. Текущее поведение роутера позволяет лишь продублировать системный механизм, а потому выглядит несколько бесполезно т.к. зачем мне еще одна кнопка, при наличии системной? Тогда как более сложное поведение привносило бы дополнительную ценность, за счет однозначного открытия предыдущей панели по иерархии, сохранив по возможности стандартный переход по истории.

**Comment by nshvyryaev** [comment]
Давайте представим, что у нас есть такой путь Home->Catalog->Item. Home и Catalog - панели, Item - модалка.

Пользователь входит по прямой ссылке в /catalog/item123. Закрывает модалку Item, попадает в Catalog. Жмет кнопку назад в интерфейсе приложения, попадает на Home (через push, как вы предложили, потому что back(Home) показал, что бэк идет не туда). На Home в интерфейсе кнопки назад нет, пользователь жмет назад в бразуре и оказывается опять в Catalog. Я не уверен, что такой переход будет интуитивно понятен пользователю.

**Comment by Kritolan** [comment]
Вы воспринимаете кнопку назад в первую очередь как кнопку, которая делает переход назад во времени. Я же воспринимаю ее как кнопку, которая делает переход назад по иерархии. Т.е. при нажатии на нее я не ожидаю что она приведет меня на предыдущую запись в истории, а ожидаю, что она приведет меня на главную.

Если при этом, в случаях, когда это возможно, это будет и переход по истории - это будет удобно, но это именно вторичный эффект, а не основной. Поэтому описанной выше ситуации не произойдет т.к. пользователь при нажатии назад на странице каталога, будет ожидать перехода на главную и он его получит. А при нажатии назад в браузере у него соотвественно будет уже ожидание перехода во времени.

В итоге это выглядит достаточно просто. Системное назад ознаачает переход во времени с вторичным эффектом навигации по иерархии. А кнопка внутри приложения - это в первую очередь переход по иерархии, а уже потом переход во времени. Ибо какой смысл в кнопки внутри приложения, если она дублирует системную?

**Comment by Kritolan** [comment]
Есть и другой вариант решения этой задачи. Можно добавить в роутер только поддержку ведения истории переходов и манипуляции над ней. Это выглядит, вероятно, более простым, и в то же время более гитбким решением т.к. позволит самостоятельно реализовать нужное поведение + добавит дополнительные возможности, вроде ведения раздельной истории переходов для разных View, как в нативном приложении ВК.

**Comment by pasha-nikitin-2003** [comment]
В роутере есть поддержка ведения истории переходов, в объекте ```routerNavigator.viewHistory.history``` можно посмотреть весь список. А все манипуляции над историей совершаются при помощи переходов: ```back```, ```push```, ```replace```, ```go```.

**Comment by pasha-nikitin-2003** [comment]
> Есть и другой вариант решения этой задачи. Можно добавить в роутер только поддержку ведения истории переходов и манипуляции над ней. Это выглядит, вероятно, более простым, и в то же время более гитбким решением т.к. позволит самостоятельно реализовать нужное поведение + добавит дополнительные возможности, вроде ведения раздельной истории переходов для разных View, как в нативном приложении ВК.

Рассмотрим вариант, чтобы дать разработчикам доступ к интерфейсу для взаимодействия с историей переходов,
