### ISSUE TITLE
[Bug]: vkui 7.0.0 conflict with vk-mini-apps-router 1.7.0

### ISSUE THREAD

**Issue by kpachbiu88** [VKCOM/vk-mini-apps-router#439]
### Описание

see https://github.com/VKCOM/VKUI/issues/8059

### Версия vk-mini-apps-router

1.7.0

### Платформа

Web

### Шаги воспроизведения

None

### Ожидаемое поведение

None

### Фактическое поведение

None

**Comment by pasha-nikitin-2003** [comment]
Спасибо за обращение, исследуем и возьмем в работу.

**Comment by pasha-nikitin-2003** [comment]
В версии роутера 1.7.1 исправили проблему.
